Switch to DemoCards.jl
CarloLucibello/GraphNeuralNetworks.jl pull request #206
Opened 2022-09-29 09:29 UTC by Dsantra92

Adding cache files for reduced time on CI. With a few more notebooks, CI would fail.

Merge after [DemoCards.jl pluto pr](https://github.com/JuliaDocs/DemoCards.jl/pull/121)

Screenshots:
![screenshot1](https://user-images.githubusercontent.com/55111154/192995536-9bb3dd10-08f3-4aa9-96ac-cc78edc06899.png)
![screenshot](https://user-images.githubusercontent.com/55111154/192995539-ca15667a-1da8-477d-afff-860594441f89.png)

2022-09-29 12:03 UTC, CarloLucibello commented
Nice, I'll wait https://github.com/JuliaDocs/DemoCards.jl/pull/121 before testing locally

2022-10-04 08:52 UTC, CarloLucibello requested changes

2022-10-04 08:52 UTC, CarloLucibello commented on docs/Project.toml
> +DemoCards = "311a05b2-6137-4a5a-b473-18580a3d38b5"
we need compat bounds here

2022-10-04 11:50 UTC, CarloLucibello commented
The doc CI is still failing

2022-10-04 12:15 UTC, Dsantra92 commented
Looking into it shortly.

2022-10-04 12:19 UTC, Dsantra92 commented
Is the latest version of DemoCards locally available? I think I messed up the release 🙁. Didn't use a tagbot.

2022-10-04 12:29 UTC, CarloLucibello commented
see [here](https://github.com/JuliaDocs/DemoCards.jl/commit/68665066201d89a2e95f27489bd42117cc8771a8#commitcomment-85795525)

2022-10-04 18:00 UTC, Dsantra92 commented
The docs are failing because I changed the pluto files themselves, working on it.

2022-10-05 02:40 UTC, Dsantra92 commented
Managing rendered files can be a pain. Adding a CRON job later for running the files and saving them (committed by some GitHub bot) after some weeks make sense.

2022-10-05 02:41 UTC, Dsantra92 commented
Due to local rendering the pages should have effect of https://github.com/JuliaDocs/DemoCards.jl/pull/126. So no blocking pr.

2022-10-05 04:45 UTC, CarloLucibello commented
The markdown outputs shouldn't be committed, right?

2022-10-05 04:55 UTC, CarloLucibello commented
ok, let's keep them. So this is good to go?

2022-10-05 05:06 UTC, Dsantra92 commented
Just check things again locally on your machine and we are good to go.

2022-10-07 03:09 UTC, CarloLucibello commented
I tested it locally and the notebooks look fine. The tutorial landing page looks like this:
<img width="1242" alt="Screenshot 2022-10-07 at 05 00 36" src="https://user-images.githubusercontent.com/7014210/194459033-ecc44620-8c14-4910-b2bf-ce21395329b1.png">

The double "Tutorials" header is not nice, let's avoid the subsection and let's just write a few introductory lines also inviting people to contribute, e.g. something like "You will find below some tutorials showing different features of GraphNeuralNetworks.jl ..... Users are welcome to contribute their own demonstrations". 

Also, it would be nice to have a separate and related image for each card.

2022-10-09 19:10 UTC, Dsantra92 commented
Preview:
![image](https://user-images.githubusercontent.com/55111154/194775203-07d2e0bf-4775-4afd-ab1f-f2756e90d284.png)

2022-10-11 06:43 UTC, Dsantra92 commented
The documentation does not use the cached md files. I wonder why SHA of the files in my computer and that of the CI doesn't match.

2022-10-14 22:50 UTC, Dsantra92 commented
Something is acting weird with the pluto notebooks cache. Let's remove that for the time being and merge?

2022-10-15 08:23 UTC, CarloLucibello commented
> Something is acting weird with the pluto notebooks cache. Let's remove that for the time being and merge?

ok

2022-10-16 08:05 UTC, Dsantra92 commented
Ready to merge

2022-10-16 08:49 UTC, merged